Repository idearium/cli, pull requests merged in 2019-05, with the labels that each got.

#21 set mongo version
  CHANGELOG.md
  bin/c-mongo-connect.js
  bin/c-mongo-download.js
  bin/c-mongo-import.js
  package.json
Labels: review:scott

#22 Added a collection argument to `c mongo` commands
  CHANGELOG.md
  CONTRIBUTING.md
  bin/c-mongo-download.js
  bin/c-mongo-import.js
  bin/c-mongo-sync.js
  package.json
Labels: review:allan, review:dino, type:improvement

#23 Mongo connect arguments
  CHANGELOG.md
  bin/c-mongo-connect.js
  bin/c-mongo-download.js
  bin/c-mongo-import.js
  package.json
Labels: review:allan, review:dino, type:improvement

#17 Minikube profiles
  .vscode/settings.json
  CHANGELOG.md
  bin/c-mk-delete.js
  bin/c-mk-docker-env.js
  bin/c-mk-hosts.js
  bin/c-mk-ip.js
  bin/c-mk-restart.js
  bin/c-mk-start.js
  bin/c-mk-stop.js
Labels: review:allan

#24 Fixes mongo commands where database names differ
  CHANGELOG.md
  bin/c-mongo-import.js
  package.json
Labels: review:allan, type:bug
